### ISSUE TITLE
Stop catching exceptions, throw them to the caller instead

### ISSUE THREAD

**Issue by guilhermeoliveiradecarvalho** [profesorfalken/WMI4Java#8]
The current implementation of WMI4Java doesn't allow developers to catch exceptions when calling methods, instead it logs the exception and returns an empty result.

This behavior isn't wrong, and some applications/libraries need to work like that. However in my opinion a library that works with system resources -- like WMI4Java -- shouldn't catch the exception, it should throw the exception to the caller method and let the developer decide how their code should act in the event of a failure.

For example, if the RPC (remote procedure call -- used to query WMI) server can't respond at the moment I'm querying WMI on a remote machine, PowerShell throws me an error. Instead of throwing the exception and giving me the exception object, `WMI4Java` catches the exception that `WMIPowerShell` threw and logs the error. If my code needs to know what happened, it will need to read from `System.err`, and unfortunately this introduces both code and execution overhead.

**Comment by profesorfalken** [comment]
Hello, 

You are totally right. I do not remember why I decided to just log the error and return an empty response.

I am going to make a new version in which I will throw WMIException (that will be refactored to be a non checked exception).

Thanks for noticing it out.

**Comment by guilhermeoliveiradecarvalho** [comment]
I think that WMIException shouldn't be an unchecked exception. Unchecked exceptions are used for errors in the code, and WMIException can represent both errors on WMI queries themselves or even an error that's outside the programmer's control. It should be a checked exception instead (just like it is now).

**Comment by profesorfalken** [comment]
Hello, 

Some years ago I would agree with you. What you say is what Oracle/Sun have always recommended. 

However, today in modern Java, things have changed. There is not point to start a discussion here, because there is already a lot of literature. Here you are some links I have collected after a quick search:

http://tutorials.jenkov.com/java-exception-handling/checked-or-unchecked-exceptions.html
http://literatejava.com/exceptions/checked-exceptions-javas-biggest-mistake/
https://testing.googleblog.com/2009/09/checked-exceptions-i-love-you-but-you.html
https://blog.philipphauer.de/checked-exceptions-are-evil/

If, for example, you check many of the Java new APIs you will find that the checked exceptions are not used any more:
https://github.com/akullpp/awesome-java

Anyway, thank you for your tips. I have already coded a new implementation and adapted the tests for a future 1.6 version.
Thanks again!

**Comment by guilhermeoliveiradecarvalho** [comment]
Well, didn't know that you could catch unchecked exceptions. Checked exceptions are certainly going to be extinct at some point. Thanks for that.
Also, should I wait for the Maven release to close this or can I close it right now? The issue is fixed if you build from `master`.

**Comment by profesorfalken** [comment]
Hello, 

Thanks to you. I have already pushed the modifications to Maven central so the 1.6 version should be ready in 1-2 hours from now.
I close the issue.
Best regards
